import { createStitches, defaultThemeMap } from "@stitches/react";
import { colors } from "@styles/colors";

const stitches = createStitches({
  media: {
    mp: "(width >= 20em)",
    mm: "(width >= 24em)",
    mg: "(width >= 28em)",
    t: "(width >= 48em)",
    dp: "(width >= 64em)",
    dm: "(width >= 90em)",
    dg: "(width >= 160em)",
  },
  themeMap: {
    ...defaultThemeMap,
    width: "space",
    height: "space",
    opacity: "opacity",
  },
  theme: {
    colors,
    transitions: {
      width: "width 0.5s",
      height: "height 0.5s",
      transform: "transform 0.5s",
    },
    fonts: {
      heading: "DMSans",
      text: "Rubik",
    },
    sizes: {
      px: "1px",
      0: "0px",
      1: "0.25em",
      2: "0.5em",
      3: "0.75em",
      4: "1em",
      5: "1.25em",
      6: "1.5em",
      7: "1.75em",
      8: "2em",
      10: "2.5em",
      12: "3em",
      16: "4em",
      20: "5em",
      32: "8em",
      40: "10em",
      64: "16em",
      80: "20em",
    },
    space: {
      px: "1px",
      0: "0px",
      1: "0.25em",
      2: "0.5em",
      3: "0.75em",
      4: "1em",
      5: "1.25em",
      6: "1.5em",
      7: "1.75em",
      8: "2em",
      10: "2.5em",
      12: "3em",
      16: "4em",
      20: "5em",
      24: "6em",
      32: "8em",
      40: "10em",
      50: "12.5em",
      64: "16em",
      80: "20em",
    },
    fontSizes: {
      xxs: "0.625em",
      xs: "0.75em",
      sm: "0.875em",
      md: "1em",
      lg: "1.125em",
      xl: "1.25em",
      "2xl": "1.5em",
      "4xl": "2em",
      "5xl": "2.25em",
      "6xl": "3em",
      "7xl": "4em",
      "8xl": "4.5em",
      "9xl": "6em",
    },
    fontWeights: {
      regular: "regular",
      medium: "medium",
      bold: "bold",
    },
    lineHeights: {
      starter: "120%",
      short: "140%",
      base: "160%",
      tall: "180%",
    },
    borderWidths: {
      thin: "1px",
      medium: "1.5px",
      thick: "2px",
      heavy: "4px",
    },
    radii: {
      xs: "2.5px",
      sm: "5px",
      md: "10px",
      ls: "20px",
      full: "8192px",
    },
    opacity: {
      default: "100%",
      semiopaque: "90%",
      intense: "75%",
      medium: "50%",
      light: "25",
      semitransparent: "10%",
    },
    zIndices: {
      overlay: 2,
      modal: 3,
    },
  },
});

export { stitches };
